### ISSUE TITLE
Use of this tool will be banned.

### ISSUE THREAD

**Issue by SmallMix** [qfournetworks/GenshinUncap#1]
Test only once
只使用一次進行測試
![unnamed](https://user-images.githubusercontent.com/27455444/96442974-81ce8600-123e-11eb-863e-1b713b0a2553.png)

**Comment by VYRNACH** [comment]
Been playing for almost a week without problems until a possible banwave today. Main account banned for a few days
![20201019202846_1](https://user-images.githubusercontent.com/19713025/96454251-2d330700-124e-11eb-8abd-04148b5b1300.jpg)

**Comment by broodjekaas92** [comment]
Can confirm, this gave me a 3 day ban.
Thank god for not being a permanent ban.

**Comment by MaybeJulien** [comment]
This also gave me a ban

**Comment by MaybeJulien** [comment]
Anyone know how i can get in contact with them since I cant use the in game one anymore

**Comment by qfournetworks** [comment]
Will be fixed soon :)

**Comment by qfournetworks** [comment]
Update released
