### ISSUE TITLE
When launching the tool

### ISSUE THREAD

**Issue by TomerA097** [qfournetworks/GenshinUncap#2]
Hi,
When I'm trying to run this tool I get the next error:
"Please download the latest version of GenshinUncap"
I've downloaded the latest version from the releases from here, but still I get this error.

![image](https://user-images.githubusercontent.com/29170311/96580214-9cf1d200-12e0-11eb-8d7b-a4bb8a5e815c.png)

**Comment by sern19** [comment]
Please read readme file - developer of this tool temporarily disabled it because of recent ban wave. We are still waiting for update (and till the ban ends)

**Comment by qfournetworks** [comment]
there is an update now :D
