### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by spaikbes** [qfournetworks/GenshinUncap#3]
BSOD after launch TestBypass.exe or "Start" button in GenshinUncapLauncher.exe.
Error log:
 0x0000001e (0xffffffffc0000005, 0x00007ff753c4549d, 0x0000000000000000, 0x0000000000000000).

**Comment by qfournetworks** [comment]
i will try to figure out why this happens... Could you check if you have Hyper-V activated ? 
https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v#:~:text=To%20disable%20Hyper%2DV%20in,Hyper%2DV%20Hypervisor%20check%20box.

**Comment by spaikbes** [comment]
> Could you check if you have Hyper-V activated ?
Hyper-V unchecked, not active.

**Comment by qfournetworks** [comment]
Okay i will release an update to fix this. It will maybe take a bit, but it has something todo with different pc system setups so would be nice if you could give me your specs.

**Comment by spaikbes** [comment]
cpu: AMD Ryzen r9 3900XT
ram: 32GB
gpu: GTX 1080ti
os: Windows 10 x64 (2004)

**Comment by ArtByFen** [comment]
Also getting BSOD on Test or LAUNCH.
Intel i7-6700 
32 GB Ram
1070 strix
Running custom Tweaked Windows OS.

**Comment by qfournetworks** [comment]
Okay guys... Could you give me your windows build versions by pressing Windows + R and then winver 
![image](https://user-images.githubusercontent.com/42522932/97094097-ec722e00-1651-11eb-8455-84dc7f3beba3.png)

**Comment by spaikbes** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/26886778/97094151-e03e9e80-165a-11eb-935f-b979ca70bf04.png)

**Comment by qfournetworks** [comment]
The bluescreen issue should be fixed.
