### ISSUE TITLE
can't open the launcher 

### ISSUE THREAD

**Issue by Erisetta** [qfournetworks/GenshinUncap#5]
hello i'm having trouble getting the launcher to work. everytime i open the game then go to open the uncap launcher it says "could not inject, please ensure that you have the latest version of genshinUncap" i don't have any antivirus installed like avg but i do have avg tuneup i did have valorant but barely played it so unistalled it along with valoguard whatever it's called. i was also having trouble wrapping my head around how to install it properly so if someone could help please do.[
![download](https://user-images.githubusercontent.com/73242080/96740043-738f7f80-138e-11eb-90bb-440bdd9488b1.png)
](url)

**Comment by qfournetworks** [comment]
Solved via Discord :D
